services:
  nest-database:
    image: postgres
    container_name: nest-database

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-database

    ports:
      - "5432:5432"

    restart: always

    networks:
      - nest-network

    volumes:
      - postgres-data:/var/lib/postgresql/data

  api-nest:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=nest-database

    restart: always

    depends_on:
      - nest-database

    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  postgres-data: