services:
  nest-database:
    image: postgres
    container_name: nest-database

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-database

    ports:
      - "5432:5432"

    restart: always
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: